### ISSUE TITLE
Rename GeoJSON.js to gjtk.js.

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/gjtk-js#16]
`gjtk` does revolve around the GeoJSON specification, but the question is: is that name the most descriptive for that file?

**Comment by mbaptist23** [comment]
I think both names are a bit vague to be honest, but understand where you are coming from. `GeoJSON toolkit` is not the shortest name, but without knowing that `gjtk` stood for `GeoJSON toolkit` I wouldn't know what `gjtk` stands for either. I'd recommend gjtk.js to be consistent with the project, but possibly a renaming altogether. Feel free to bash these thoughts, I'm just brainstorming.

**Comment by dmtucker** [comment]
A couple of things with that:

* Changing the name of the entire project would be visible to devs currently using it (unless we still published to NPM under `gjtk`, but then what's the point?) _in addition to_ the APIs we'll be breaking in 2.0.0.
* Something I like about "gjtk" is that it is pretty unique ([Google "gjtk"](https://www.google.com/?q=gjtk)), and what it stands for is clear in the docs/repo.

Naming the repo after the main file seems to be a common practice which also seems to suggest renaming to `gjtk.js` wouldn't be a bad way to go.

**Comment by dmtucker** [comment]
Ok, this is going to happen.

https://www.npmjs.com/package/geojson

GeoJSON already exists!
