### ISSUE TITLE
GPL license is too restrictive

### ISSUE THREAD

**Issue by dbkaplun** [dmtucker/gjtk-js#24]
Would be great if you could move gjtk-js to a less restrictive license like MIT. balderdashy/anchor, SailsJS's validation library, depends on gjtk-js, but will be forced to remove it since GPL is too restrictive.

Related: [balderdashy/anchor#49](https://github.com/balderdashy/anchor/pull/49#issuecomment-129902268)

**Comment by dmtucker** [comment]
Looks like the ship has sailed, but I'll switch it to MIT in the next release.
Consider this express written consent to do anything that would be permitted by the MIT license.
